# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Static Storybook

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Test secrets
      shell: bash
      env:
        TEST: ${{ secrets.TEST_SECRET }}
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}    
      if: env.TEST != null   
      run: echo $TEST
    
    - name: Build with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
   
    - name: Run NPM Install main deps
      run: npm install # Install npm deps.

    - name: NPM Install FontAwesome Peer
      env: # Or as an environment variable
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}    
      run: |
        npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_NPM_AUTH_TOKEN
        npm install @fortawesome/fontawesome-pro #Install FA peer-dep.
        ls ./node_modules/@fortawesome/
        
    - name: Build Storybook
      run: npm run build-storybook # Run build-storybook.
    
    - name: Deploy to GH Pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: storybook-static # The folder the action should deploy.
