# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Static Storybook

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Test
      shell: bash
      env: # Or as an environment variable
        TEST: ${{ secrets.TEST_SECRET }}
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}    
      if: env.TEST != null   
      run: echo $TEST
    
    - name: Build with Node.js ${{ matrix.node-version }}
      env: # Or as an environment variable
        TEST: ${{ secrets.TEST_SECRET }}
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}    
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo $TEST
    - run: npm config set "@fortawesome:registry" https://npm.fontawesome.com/
    - run: npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_NPM_AUTH_TOKEN
    - run: npm install # Install npm deps.
    - run: npm install @fortawesome/fontawesome-pro #Install FA peer-dep.
    - run: npm run build-storybook # Run build-storybook.
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: storybook-static # The folder the action should deploy.
